# Generated by Django 4.0.3 on 2022-05-12 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='media')),
                ('date_uploaded', models.DateTimeField(default=datetime.timezone)),
            ],
        ),
    ]
