# Generated by Django 4.0.3 on 2022-05-12 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
