# Generated by Django 4.0.3 on 2022-05-12 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_videoupload_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
